<?php

/**
 * Implements hook_file_validate().
 */
function file_same_file_validate($file) {
  $errors = array();
  //\Drupal\ko\Debug::watchdog($file);
  foreach (filehash_algos() as $algo) {
    // @todo Consider using filemime as well.
    $query = db_select('filehash', 'fh')
      ->fields('fh', array('fid'));
    $query->join('file_managed', 'fm', 'fh.fid = fm.fid');
    $db_condition = db_and()->condition('fh.' . $algo, hash_file($algo, $file->uri))->condition('fm.filesize', $file->filesize);
    $query->condition($db_condition);
    $fid = $query->execute()->fetchField();
    //\Drupal\ko\Debug::watchdog($fid);
    if ($fid) {
      $file_orig = file_load($fid);
      // Copy data to the filesystem if the file is not exist.
      if (!file_exists($file_orig->uri)) {
        //$errors[] = t('File fid @fid is not exist in the filesystem, deal with it first.', array('@fid' => $fid));
        file_unmanaged_copy($file->uri, $file_orig->uri, FILE_EXISTS_REPLACE);
      }
      $file->fid = $fid;
      break;
    }
  }

  return $errors;
}
